---
- name: Set Python3 as interpreter explicitly
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: Download and install Kali archive GPG key
  ansible.builtin.shell: |
    curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /usr/share/keyrings/kali-archive-keyring.gpg --yes

- name: Install required packages
  apt:
    name:
      - nmap
      - gobuster
      - ffuf
      - wordlists
      - hydra
      - python3
      - dirbuster
      - python3-pip
      - evil-winrm
      - p7zip-full
      - metasploit-framework
    state: present
    update_cache: yes

- name: Ensure '[ "$PWD" != "/home/kali" ] && cd /home/kali' is present in .zshrc
  become_user: kali
  lineinfile:
    path: /home/kali/.zshrc
    line: '[ "$PWD" != "/home/kali" ] && cd /home/kali'
    insertafter: EOF
    state: present

- name: Ensure directory exists with correct ownership
  file:
    path: /home/kali/Desktop/ela
    state: directory
    owner: kali
    group: kali
    mode: '0755'

- name: Copy all files to ela
  copy:
    src: "../files/"
    dest: "/home/kali/Desktop/ela/"
    owner: "kali"
    group: "kali"
    mode: "0644"

- name: Create targets.txt with target IP
  copy:
    dest: /home/kali/Desktop/ela/linux/targets.txt
    content: 10.{{ range_second_octet }}.20.12
    owner: kali
    group: kali
    mode: '0644'

- name: Clone Impacket repository
  git:
    repo: https://github.com/fortra/impacket.git
    dest: /home/kali/Desktop/ela/windows/impacket

- name: Install Flask with --break-system-packages
  ansible.builtin.pip:
    name: flask
    extra_args: --break-system-packages
    executable: pip3

- name: Install Python requirements with --break-system-packages
  ansible.builtin.pip:
    requirements: requirements.txt
    extra_args: --break-system-packages
    executable: pip3
    chdir: /home/kali/Desktop/ela/windows/impacket

- name: Enable vnc
  ansible.builtin.include_tasks: 
    file: vnc.yml