---
- name: Reinstall ca-certificates
  apt:
    name: ca-certificates
    state: present
    force: yes

- name: Install lsb-release and wget
  apt:
    name:
      - lsb-release
      - wget
    state: present

- name: Download Packetbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-8.17.3-amd64.deb
    dest: /tmp/packetbeat-8.17.3-amd64.deb

- name: Install Packetbeat
  apt:
    deb: /tmp/packetbeat-8.17.3-amd64.deb

- name: Download Auditbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.17.3-amd64.deb
    dest: /tmp/auditbeat-8.17.3-amd64.deb

- name: Install Auditbeat
  apt:
    deb: /tmp/auditbeat-8.17.3-amd64.deb

- name: Download Filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.17.3-amd64.deb
    dest: /tmp/filebeat-8.17.3-amd64.deb

- name: Install Filebeat
  apt:
    deb: /tmp/filebeat-8.17.3-amd64.deb

- name: Install missing dependencies
  apt:
    name: '*'
    state: latest
    force_apt_get: yes

- name: Copy multiple configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0600"
  loop:
    - { src: "../files/packetbeat.yml", dest: "/etc/packetbeat/packetbeat.yml" }
    - { src: "../files/filebeat.yml", dest: "/etc/filebeat/filebeat.yml" }
    - { src: "../files/auditbeat.yml", dest: "/etc/auditbeat/auditbeat.yml" }
    - { src: "../files/apache.yml", dest: "/etc/filebeat/modules.d/apache.yml" }
    - { src: "../files/mariadb.yml", dest: "/etc/filebeat/modules.d/mariadb.yml" }

- name: Set Beats variables
  set_fact:
    beats_config_files:
      - /etc/filebeat/filebeat.yml
      - /etc/packetbeat/packetbeat.yml
      - /etc/auditbeat/auditbeat.yml

- name: Replace USER_SECOND_OCTET in all config files
  replace:
    path: "{{ item }}"
    regexp: '10\.USER_SECOND_OCTET\.20\.11'
    replace: "10.{{ range_second_octet  }}.20.11"
  loop: "{{ beats_config_files }}"

- name: Replace USERNAME in all config files
  replace:
    path: "{{ item }}"
    regexp: 'USERNAME'
    replace: "{{ elastic_username }}"
  loop: "{{ beats_config_files }}"

- name: Replace PASSWORD in all config files
  replace:
    path: "{{ item }}"
    regexp: 'PASSWORD'
    replace: "{{ elastic_password }}"
  loop: "{{ beats_config_files }}"

- name: Setup Packetbeat
  command: packetbeat setup

- name: Setup Auditbeat
  command: auditbeat setup

- name: Setup Filebeat
  command: filebeat setup

- name: Enable Filebeat Apache module
  command: filebeat modules enable apache

- name: Enable Filebeat Mariadb module
  command: filebeat modules enable mariadb

- name: Restart Packetbeat
  systemd:
    name: packetbeat
    state: restarted
    enabled: yes

- name: Restart Auditbeat
  systemd:
    name: auditbeat
    state: restarted
    enabled: yes

- name: Restart Filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
