#packetbeat.interfaces.device: any
packetbeat.interfaces.device: 0

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
- type: icmp
  enabled: true

- type: amqp
  ports: [5672]

- type: cassandra
  ports: [9042]

- type: dhcpv4
  ports: [67, 68]

- type: dns
  ports: [53, 8053, 5353]
  include_authorities: true
  include_additionals: true

- type: http
  ports: [80, 81, 8080, 8081, 8000, 5000, 8002]

- type: memcache
  ports: [11211]

- type: mysql
  ports: [3306,3307]

- type: pgsql
  ports: [5432]

- type: redis
  ports: [6379]

- type: thrift
  ports: [9090]

- type: mongodb
  ports: [27017]

- type: nfs
  ports: [2049]

- type: tls
  ports:
    - 443   
    - 993   
    - 995   
    - 5223  
    - 8443
    - 8883  
    - 9243  

- type: sip
  ports: [5060]

- type: ssh
  ports: [22, 2222]

- type: tcp
  ports: [0-1024]  

- type: udp
  ports: [0-1024]  

setup.ilm.overwrite: true

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  #host: "https://10.USER_SECOND_OCTET.20.11:5601"
  host: "https://10.5.20.11:5601"
  ssl.verification_mode: none

output.elasticsearch:
  #hosts: ["https://10.USER_SECOND_OCTET.20.11:9200"]
  hosts: ["https://10.5.20.11:9200"]
  username: "elastic" 
  #username: "USERNAME" 
  password: "S3cur3P@ss?"
  #password: "PASSWORD"
  ssl.verification_mode: none

processors:
  - 
    if.contains.tags: forwarded
    then:
      - drop_fields:
          fields: [host]
    else:
      - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - detect_mime_type:
      field: http.request.body.content
      target: http.request.mime_type
  - detect_mime_type:
      field: http.response.body.content
      target: http.response.mime_type