filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
  - type: journald
    tags: ["systemd", "ssh", "cron"]
    include_matches:
      - "UNIT=ssh.service"
      - "UNIT=cron.service"
    processors:
      - add_fields:
          fields:
            service: "ssh"
      - add_fields:
          fields:
            service: "cron"

setup.ilm.overwrite: true

setup.kibana:
  host: "https://10.USER_SECOND_OCTET.20.11:5601"
  ssl.verification_mode: none

output.elasticsearch:
  hosts: ["https://10.USER_SECOND_OCTET.20.11:9200"]
  username: "USERNAME" 
  password: "PASSWORD"
  ssl.verification_mode: none

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~